---
  - name: Create Destination Directory if not exists
      file:
        path: "{{ destination_directory }}"
        state: directory
      when: not (destination_directory is exists)
  - name: Download Putty installer
    win_get_url:
      url: https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.80-installer.msi
      dest: C:\Temp\putty_installer.msi
  - name: Install Putty silently
    win_shell: |
      Start-Process -FilePath "C:\Temp\putty_installer.msi" -ArgumentList "/quiet" -Wait
  - name: Remove Putty installer
    win_file:
      path: C:\Temp\putty_installer.msi
      state: absent
   
