---
  - name: Download Firefox Installer
    win_get_url:
      url: "https://download.mozilla.org/?product=firefox-latest&os=win64&lang=en-US"
      dest: C:\Temp\firefox-installer.exe
  - name: Run Firefox Installer
    win_shell: |
      Start-Process -FilePath "C:\Temp\firefox-installer.exe" -Wa
