---
  - name: Download Firefox to specified path
    win_get_url:
      url: https://download.mozilla.org/?product=firefox-latest-ssl&os=win64&lang=en-US
      dest: C:\Windows\Temp\firefox2.exe
  - name: Install Firefox
    win_package:
      path: C:\Windows\Temp\firefox2.exe
     product_id: auto
      wait: no
      state: present
