---
  - name: Download Firefox Installer
    win_get_url:
      url: "{{ firefox_url }}"
      dest: "{{ firefox_install }}"
  - name: Run Firefox Installer
    win_shell: |
      Start-Process -FilePath "{{ firefox_install }}" -Wait
