---
- name: "Chocolatey Install"
  hosts: localhost
  become: true
  become_method: su
  tasks:
    - name: Install chocolatey
      win_chocolatey:
          name:
           - chocolatey
           - chocolatey-core.extension
          state: present
