---

- name: Read CSV and Create AD Users
  win_domain_user:
    name: "{{ item.first_name[0] | lower }}{{ item.last_name | lower }}"
    firstname: "{{ item.first_name }}" 
    surname: "{{ item.last_name }}" 
    display_name: "{{ item.first_name }}{{ item.last_name }}"
    password: "{{ item.password }}"
    state: present
    path: "{{ item.ou }}"
    groups:
      - "{{ item.group }}"
    password_never_expires: false
  with_items: "{{ users }}"
  loop_control:
    loop_var: item

- name: Read CSV File
  set_fact:
    users: "{{ lookup('csvfile', role_path + '/files/users.csv', wantlist=True) }}"
