---

- name: Create AD User
  win_domain_user:
    name: "{{ firstname[0] | lower }}{{ surname | lower }}"
    firstname: Khalan 
    surname: Bridewell 
    display_name: "{{ firstname }}{{ surname }}"
    company: Student
    password: subst@NTI@l
    state: present
    path: ou=admin,ou=accounts,ou=bwells,dc=stevenslab,dc=local
    groups:
      - Domain Admins
    password_never_expires: false

