---

- name: Create AD User
  win_domain_user:
    name: sbridewell2
    firstname: Steven 
    surname: Bridewell JR
    display_name: Steven Bridewell JR
    company: Student
    description: Steven Jr Test Admin Account
    password: subst@NTI@l
    state: present
    path: ou=admin,ou=accounts,ou=bwells,dc=stevenslab,dc=local
    groups:
      - Domain Admins
    password_never_expires: true
    street: 12345 Somewhere Lane
    city: Lancaster
    state_province: CA
    postal_code: 93535
    country: US
