---

- name: Create AD User
  win_domain_user:
    name: "{{ first_name[0] | lower }}{{ last_name | lower }}"
    firstname: "{{ first_name }}" 
    surname: "{{ last_name }}" 
    display_name: "{{ first_tname }}{{ last_name }}"
    password: "{{ password }}"
    state: present
    path: ou=admin,ou=accounts,ou=bwells,dc=stevenslab,dc=local
    groups:
      - Domain Admins
    password_never_expires: false

