---
  - name: Download Chrome to specified path
    win_get_url:
      url: https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B3862AEED-5880-BE05-AB03-7175B09D273B%7D%26lang%3Den%26browser%3D3%26usagestats%3D0%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-stable-statsdef_1%26installdataindex%3Dempty/chrome/install/ChromeStandaloneSetup64.exe
      dest: C:\Windows\Temp\chrome.exe
  - name: Install Chrome
    win_package:
      path: C:\Windows\Temp\chrome.exe
      product_id: auto
      wait: yes
      state: present
   
