---

- name: Ensure user bob is created and use custom credentials to 
  win_domain_user:
    name: abridewell
    password: subst@NTI@l
    state: present
    path: ou=admin,ou=accounts,ou=bwells,dc=stevenslab,dc=local
    groups:
      - Domain Admins
- name: Add a domain user/group to a domain group
  win_domain_group_membership:
    name: Domain Admins
    members:
      - stevenslab.local\abridewell
    state: present
