---

- name: Add Users to Active Directory
  win_domain_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
    ou: "{{ item.ou }}"
  with_items:
    - { username: 'user1', password: 'password1', ou: 'OU=Sales,DC=example,DC=com' }
    - { username: 'user2', password: 'password2', ou: 'OU=IT,DC=example,DC=com' }
    # Add more users as needed
- name: Add Users to AD Group
  win_domain_group_membership:
    name: "GroupName"  # Specify the AD group name
    members: 
      - "{{ item.username }}"
    state: present
  with_items:
    - { username: 'user1' }
    - { username: 'user2' }
    # Add more users as needed


