---

- name: Add Users to Active Directory
  win_domain_user:
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
    ou: "{{ item.ou }}"
  with_items:
    - { username: 'criley', password: 'password1', ou: 'OU=Admin,OU=Accounts,OU=BWELLS,DC=stevenslab,DC=local' }
    - { username: 'cboyd', password: 'password2', ou: 'OU=Admin,OU=Accounts,OU=BWELLS,DC=stevenslab,DC=local' }
    # Add more users as needed
- name: Add Users to AD Group
  win_domain_group_membership:
    name: "GroupName"  # Specify the AD group name
    members: 
      - "{{ item.username }}"
    state: present
  with_items:
    - { username: 'criley' }
    - { username: 'cboyd' }
    # Add more users as needed


