- name: Add User Account
  microsoft.ad.user:
    name: Aaliyah
    password: password01
    state: present
    path: ou=Admin,ou=Accounts,ou=Bwells,dc=stevenslab,dc=local
    groups:
      - Domain Admins
