---

- name: Ensure user/s are present with address information
  win_domain_user:
    name: cboyd
    firstname: Cameron
    surname: Boyd
    display_name: Cameron Boyd
    company: Student
    password: subst@NTI@l
    state: present
    path: ou=admin,ou=accounts,ou=bwells,dc=stevenslab,dc=local
    street: 13163 Fountain Park Drive
    city: Playa Vista
    state_province: CA
    postal_code: 90094
    country: US
    attributes:
      telephoneNumber: 555-654321
- name: Add a domain user/group to a domain group
  win_domain_group_membership:
    name: Domain Admins
    members:
      - stevenslab.local\cboyd
    state: present
