---

- name: Create Domain User
  win_domain_user:
    name: "{{ username }}"
    password: "{{ user_password }}"
    state: present
    groups: "{{ groups }}"
        # Add other parameters as needed
  #delegate_to: localhost
