- name: Add User Account
  win_domain_user:
    name: Aaliyah
    password: password01
    state: present
    path: ou=Admin,ou=Accounts,ou=Bwells,dc=stevenslab,dc=local
    groups:
      - Domain Admins
