---

- name: Ensure user bob is present with address information
  win_domain_user:
    name: criley
    firstname: Chris
    surname: Riley
    display_name: Christopher Riley
    company: Cinemark
    password: password01
    state: present
    groups:
      - Domain Admins
    street: 13163 Fountain Park Drive
    city: Playa Vista
    state_province: CA
    postal_code: 90094
    country: US
    attributes:
      telephoneNumber: 555-123456
