- name: Ensure Temp Directory Exists
  win_file:
    path: C:\Temp
    state: directory

- name: Download Malwarebytes Installer
  win_get_url:
    url: "{{ malwarebytes_installer_url }}"
    dest: "{{ malwarebytes_installer_path }}"
    force: yes

- name: Install Malwarebytes
  win_command:
    cmd: "{{ malwarebytes_installer_path }} {{ malwarebytes_install_args }}"
  register: malwarebytes_install_result
  changed_when: malwarebytes_install_result.rc == 0

- name: Verify Malwarebytes Installation
  win_stat:
    path: "{{ malwarebytes_install_dir }}"
  register: malwarebytes_installed

- name: Display Installation Status
  debug:
    msg: "Malwarebytes is installed"
  when: malwarebytes_installed.stat.exists

