galaxy_info:
  author: "Steven Bridewell"
  description: "Installs Malwarebytes on Windows machines"
  license: "MIT"
  min_ansible_version: "2.10"
  platforms:
    - name: Windows
      versions:
        - all
  categories:
    - security
dependencies: []

